### ISSUE TITLE
Level this! and NightVision conflict

### ISSUE THREAD

**Issue by marleyKuhl** [AndTheManDrew/NightVision#3]
https://pastebin.com/nnPLNALE
the could not load reference to was because i took out a lot of other mods to make it so the player log would actually fit on pastebin.

**Comment by marleyKuhl** [comment]
i'm having this problem on both my mac and pc, so i can post my player log from there as well if you'd like

**Comment by AndTheManDrew** [comment]
Thanks @midas22 . And yes, the player log from there as well would be helpful. You should be able to just drag and drop it here.

**Comment by marleyKuhl** [comment]
i apologize, but the problem has since gone away on my pc, but not my mac. i've been trying to see what could be different, but i have the exact same mods, and exact same mod settings, so i'm really not sure
